// apps/react-framework/src/pages/SelectRemountMultiselectNavigate.tsx
import { useEffect } from 'react';

export default function SelectRemountMultiselectNavigate() {
  useEffect(() => {
    const timer = setTimeout(() => {
      window.history.pushState({}, '', '/select-remount-multiselect');
      window.dispatchEvent(new PopStateEvent('popstate'));
    }, 200);
    return () => clearTimeout(timer);
  }, []);

  return <p>Navigating to select remount multiselect page...</p>;
}

// apps/svelte-framework/src/routes/select-remount-multiselect-navigate/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';

	onMount(() => {
		const timer = setTimeout(() => {
			goto('/select-remount-multiselect');
		}, 200);
		return () => clearTimeout(timer);
	});
</script>

<p>Navigating to select remount multiselect page...</p>
