// apps/svelte-framework/src/routes/combobox-city-search-preselected-navigate/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';

	onMount(() => {
		const timer = setTimeout(() => {
			goto('/combobox-city-search-preselected');
		}, 200);
		return () => clearTimeout(timer);
	});
</script>

<p>Navigating to preselected combobox page...</p>

// apps/react-framework/src/pages/ComboboxCitySearchPreselectedNavigate.tsx
import { useEffect } from 'react';

export default function ComboboxCitySearchPreselectedNavigate() {
  useEffect(() => {
    const timer = setTimeout(() => {
      window.history.pushState({}, '', '/combobox-city-search-preselected');
      window.dispatchEvent(new PopStateEvent('popstate'));
    }, 200);
    return () => clearTimeout(timer);
  }, []);

  return <p>Navigating to preselected combobox page...</p>;
}
