// apps/svelte-framework/src/routes/combobox-remount/+page.svelte
<script lang="ts">
	import '@aurodesignsystem/auro-formkit/auro-combobox';
	import '@aurodesignsystem/auro-formkit/auro-menu';

	const options: [string, string][] = [
		['Apples', 'Apples'],
		['Oranges', 'Oranges'],
		['Peaches', 'Peaches'],
		['Grapes', 'Grapes'],
	];

	let comboboxValue = $state<string>('Apples');
	let showCombobox = $state<boolean>(true);

	function setInvalidValue() {
		const el = document.querySelector('auro-combobox') as any;
		if (el) el.value = 'invalid-option';
	}
</script>

<button id="toggle" onclick={() => (showCombobox = !showCombobox)}>
	{showCombobox ? 'Hide' : 'Show'} Combobox
</button>
<button id="set-invalid" onclick={setInvalidValue}>Set Invalid Value</button>

{#if showCombobox}
	<auro-combobox behavior="filter" value={comboboxValue}>
		<auro-menu>
			{#each options as [value, label]}
				<auro-menuoption {value}>{label}</auro-menuoption>
			{/each}
		</auro-menu>
	</auro-combobox>
{/if}

<style>
	#toggle {
		margin-right: 1rem;
	}
</style>

// apps/react-framework/src/pages/ComboboxRemount.tsx
import { useState } from 'react';

const OPTIONS: [string, string][] = [
  ['Apples', 'Apples'],
  ['Oranges', 'Oranges'],
  ['Peaches', 'Peaches'],
  ['Grapes', 'Grapes'],
];

const INITIAL_VALUE = 'Apples';

function ComboboxWrapper() {
  return (
    <auro-combobox behavior="filter" value={INITIAL_VALUE}>
      <auro-menu>
        {OPTIONS.map(([value, label]) => (
          <auro-menuoption key={value} value={value}>{label}</auro-menuoption>
        ))}
      </auro-menu>
    </auro-combobox>
  );
}

export default function ComboboxRemount() {
  const [show, setShow] = useState(true);

  function setInvalidValue() {
    const el = document.querySelector('auro-combobox') as any;
    if (el) el.value = 'invalid-option';
  }

  return (
    <div>
      <button id="toggle" onClick={() => setShow((s) => !s)}>
        {show ? 'Hide' : 'Show'} Combobox
      </button>
      <button id="set-invalid" onClick={setInvalidValue}>Set Invalid Value</button>
      {show && <ComboboxWrapper />}
    </div>
  );
}
