// apps/svelte-framework/src/routes/select-dynamic/+page.svelte
<script lang="ts">
	import '@aurodesignsystem/auro-formkit/auro-select';
	import '@aurodesignsystem/auro-formkit/auro-menu';
	import { onMount } from 'svelte';

	const ALL_OPTIONS: [string, string][] = [
		['foo', 'Foo'],
		['bar', 'Bar'],
		['baz', 'Baz'],
	];

	let selectValue = $state<string>('bar');
	let options = $state<[string, string][]>([]);
	let showSelect = $state<boolean>(true);

	onMount(() => {
		const timer = setTimeout(() => {
			options = ALL_OPTIONS;
		}, 300);
		return () => clearTimeout(timer);
	});
</script>

<button id="toggle" onclick={() => (showSelect = !showSelect)}>
	{showSelect ? 'Hide' : 'Show'} Select
</button>

{#if showSelect}
	<auro-select value={selectValue}>
		<auro-menu>
			{#each options as [value, label]}
				<auro-menuoption {value}>{label}</auro-menuoption>
			{/each}
		</auro-menu>
	</auro-select>
{/if}

// apps/react-framework/src/pages/SelectDynamic.tsx
import { useState, useEffect } from 'react';

const ALL_OPTIONS: [string, string][] = [
  ['foo', 'Foo'],
  ['bar', 'Bar'],
  ['baz', 'Baz'],
];

const INITIAL_VALUE = 'bar';

function SelectDynamicWrapper() {
  const [options, setOptions] = useState<[string, string][]>([]);

  useEffect(() => {
    const timer = setTimeout(() => {
      setOptions(ALL_OPTIONS);
    }, 300);
    return () => clearTimeout(timer);
  }, []);

  return (
    <auro-select value={INITIAL_VALUE}>
      <auro-menu>
        {options.map(([value, label]) => (
          <auro-menuoption key={value} value={value}>{label}</auro-menuoption>
        ))}
      </auro-menu>
    </auro-select>
  );
}

export default function SelectDynamic() {
  const [show, setShow] = useState(true);

  return (
    <div>
      <button id="toggle" onClick={() => setShow((s) => !s)}>
        {show ? 'Hide' : 'Show'} Select
      </button>
      {show && <SelectDynamicWrapper />}
    </div>
  );
}
