// apps/svelte-framework/src/routes/single-counter-remount/+page.svelte
<script lang="ts">
	import '@aurodesignsystem/auro-formkit/auro-counter';

	const initialValue = 3;
	let showCounter = $state<boolean>(true);
</script>

<button id="toggle" onclick={() => (showCounter = !showCounter)}>
	{showCounter ? 'Hide' : 'Show'} Counter
</button>

{#if showCounter}
	<auro-counter value={String(initialValue)} min="0" max="9">
		Bags
		<span slot="description">Number of checked bags</span>
	</auro-counter>
{/if}

<style>
	#toggle {
		margin-bottom: 1rem;
	}
</style>

// apps/react-framework/src/pages/SingleCounterRemount.tsx
import { useState } from 'react';

const INITIAL_VALUE = 3;

function CounterWrapper() {
  return (
    <auro-counter value={String(INITIAL_VALUE)} min="0" max="9">
      Bags
      <span slot="description">Number of checked bags</span>
    </auro-counter>
  );
}

export default function SingleCounterRemount() {
  const [show, setShow] = useState(true);

  return (
    <div>
      <button id="toggle" onClick={() => setShow((s) => !s)}>
        {show ? 'Hide' : 'Show'} Counter
      </button>
      {show && <CounterWrapper />}
    </div>
  );
}
