// apps/react-framework/src/pages/SelectRemountMultiselect.tsx
import { useState } from 'react';

const OPTIONS: [string, string][] = [
  ['foo', 'Foo'],
  ['bar', 'Bar'],
  ['baz', 'Baz'],
];

const INITIAL_VALUE = '["foo","bar"]';

function SelectWrapper() {
  return (
    <auro-select multiselect value={INITIAL_VALUE}>
      <auro-menu>
        {OPTIONS.map(([value, label]) => (
          <auro-menuoption key={value} value={value}>{label}</auro-menuoption>
        ))}
      </auro-menu>
    </auro-select>
  );
}

export default function SelectRemountMultiselect() {
  const [show, setShow] = useState(true);

  function setInvalidValue() {
    const el = document.querySelector('auro-select') as any;
    if (el) el.value = '["invalid-option"]';
  }

  return (
    <div>
      <button id="toggle" onClick={() => setShow((s) => !s)}>
        {show ? 'Hide' : 'Show'} Select
      </button>
      <button id="set-invalid" onClick={setInvalidValue}>Set Invalid Value</button>
      {show && <SelectWrapper />}
    </div>
  );
}

// apps/svelte-framework/src/routes/select-remount-multiselect/+page.svelte
<script lang="ts">
	import '@aurodesignsystem/auro-formkit/auro-select';
	import '@aurodesignsystem/auro-formkit/auro-menu';

	const options: [string, string][] = [
		['foo', 'Foo'],
		['bar', 'Bar'],
		['baz', 'Baz'],
	];

	let selectValue = $state<string>('["foo","bar"]');
	let showSelect = $state<boolean>(true);

	function setInvalidValue() {
		const el = document.querySelector('auro-select') as any;
		if (el) el.value = '["invalid-option"]';
	}
</script>

<button id="toggle" onclick={() => (showSelect = !showSelect)}>
	{showSelect ? 'Hide' : 'Show'} Select
</button>
<button id="set-invalid" onclick={setInvalidValue}>Set Invalid Value</button>

{#if showSelect}
	<auro-select multiselect value={selectValue}>
		<auro-menu>
			{#each options as [value, label]}
				<auro-menuoption {value}>{label}</auro-menuoption>
			{/each}
		</auro-menu>
	</auro-select>
{/if}

<style>
	#toggle {
		margin-right: 1rem;
	}
</style>
